---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: instrumentisto/rust:nightly-alpine@sha256:92fc8e4c73ea39c92e12eebebf88712edca9bb9c37b6dec43c714b2441b6df21
    commands:
      - apk -UvX http://dl-cdn.alpinelinux.org/alpine/edge/main add -u musl-dev pkgconfig alsa-lib-dev expat-dev cmake build-base freetype-dev
      - cargo fmt --all -- --check
      - cargo clippy -- -Dwarnings
