steps:
  - name: lint
    image: instrumentisto/rust:nightly-alpine@sha256:479630387561126c15f2afb84d41dacc4f558140c3163d161a26420b81952bbc
    commands:
      - apk -UvX http://dl-cdn.alpinelinux.org/alpine/edge/main add -u musl-dev pkgconf alsa-lib-dev expat-dev cmake build-base freetype-dev
      - cargo fmt --all -- --check
      - cargo clippy -- -Dwarnings
