steps:
  - name: lint
    image: instrumentisto/rust:nightly-alpine@sha256:0a9422a9b8683fb91adfd0dc1aa6a32d4f2381ec9d749066e9feae4e8a1ca090
    commands:
      - apk -UvX http://dl-cdn.alpinelinux.org/alpine/edge/main add -u musl-dev pkgconf alsa-lib-dev expat-dev cmake build-base freetype-dev
      - cargo fmt --all -- --check
      - cargo clippy -- -Dwarnings
